version: '3.8'

services:
  site:
    image: node:20
    working_dir: /webapp
    volumes:
      - .:/webapp
    command: nodemon Node.js
    environment:
      - MONGO_URI=mongodb://site232453:ahB4ha7j@mongo_site232453:27017/admin
      - PORT=8000
    ports:
      - "8000:8000"